config/routes.rb
Rails.application.routes.draw do
  
  root 'people#index'
  resources :people do
    resources :addresses
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
  belongs_to :address_type
end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
  has_many :addresses
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses
  accepts_nested_attributes_for :addresses, allow_destroy: true

  def full_name
    self.name + " " + self.last_name
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_person, except: :new

  def index
    @addresses = @person.addresses
  end

  def new
    @address = Address.new
    @address_types = AddressType.all
  end

  def create
    @person.addresses.create(address_params)
    redirect_to person_addresses_path
  end

  def edit
    @address = Address.find(params[:id])
    @address_types = AddressType.all
    render 'new'
  end

  def update
    Address.find(params[:id]).update(address_params)
    redirect_to person_addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :country, :address_type_id)
  end

  def find_person
    @person = Person.find(params[:person_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    Person.create(person_params)
    redirect_to people_path
  end

  def edit
    @person = Person.find(params[:id])
    render 'new'
  end

  def update
    Person.find(params[:id]).update(person_params)
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person)
      .permit(:name, :last_name, :ci_number, :birthday, addresses_attributes: [:street, :city, :state, :country, :address_type_id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/addresses/index.html.slim
div.container
  div.section
    h1 Direcciones de #{@person.full_name}

  div.divider

  div.section
    - if @addresses.any?
      table#addresses.highlight.responsive-table
        tr
          th Calle
          th Ciudad
          th Estado
          th Pais
          th Tipo de Direccion
          - for address in @addresses
            tr
              td.calle = address.street
              td.ciudad = address.city
              td.estado = address.state
              td.pais = address.country
              td.tipo = address.address_type.name
              td.edit = link_to edit_person_address_path(@person, address), class: "btn-floating btn-large waves-effect waves-light blue"
                i.material-icons.medium mode_edit
    div.fixed-action-button.right-align
      = link_to "addresses/new", class: "btn-floating btn-large waves-effect waves-light red"
        i.material-icons.large add

app/views/addresses/new.html.slim
div.container
  div.row
    div.col.s12
      - if @address.new_record?
        = simple_form_for @address, url: person_addresses_path, defaults: {input_html: {class: 'validate'}} do |f|
          div.row
            div.input-field.col.s6
              = f.input :street
            div.input-field.col.s6
              = f.input :city, input_html: {class: ''}
          div.row
            div.input-field.col.s6
              = f.input :state
            div.input-field.col.s6
              = f.input :country
          div.row
            div.input-field.col.s12
              = f.association :address_type, collection: @address_types, label: false, input_html: {class: ''}
          div.row
            div.input-field.col.s12.right-align
              = f.button :submit
      - else
        = simple_form_for @address, url: person_address_path, defaults: {label:false} do |f|
          div.row
            div.input-field.col.s6
              = f.input :street
            div.input-field.col.s6
              = f.input :city, input_html: {class: ''}
          div.row
            div.input-field.col.s6
              = f.input :state
            div.input-field.col.s6
              = f.input :country
          div.row
            div.input-field.col.s12
              = f.association :address_type, collection: @address_types, selected: @address.address_type
          div.row
            div.input-field.col.s12.right-align
              = f.button :submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticaVistas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.slim
div.container
  div.section
    h1 Lista de Personas 

  div.divider

  div.section
    - if @people.any?
      table#people.highlight.responsive-table
        tr
          th Nombre
          th Apellido
          th Cedula 
          th Fecha de Nacimiento
        - @people.each do |p|
          tr
            td.nombre = p.name
            td.apellido = p.last_name
            td.cedula = p.ci_number
            td.fecha = p.birthday
            td.addresses = link_to person_addresses_path(p), action: 'get', class: "btn-floating btn-large waves-effect waves-light green"
              i.material-icons.medium home
            td.edit = link_to edit_person_path(p), class: "btn-floating btn-large waves-effect waves-light blue"
                i.material-icons.medium mode_edit
    div.fixed-action-button.right-align
      = link_to new_person_path, class: "btn-floating btn-large waves-effect waves-light red"
        i.material-icons.large add

app/views/people/new.html.slim
div.container
  div.row
    div.col.s12
      - if @person.new_record?
        = simple_form_for @person, url: people_path, defaults: {input_html: {class: 'validate'}} do |f|
          div.row
            div.input-field.col.s6
              = f.input :name
            div.input-field.col.s6
              = f.input :last_name, input_html: {class: ''}
          div.row
            div.input-field.col.s6
              = f.input :ci_number
            div.input-field.col.s6
              = f.input :birthday
          div.row
            div.input-field.col.s12.right-align
              = f.button :submit
      - else
        = simple_form_for @person, url: person_path, defaults: {label: false} do |f|
          div.row
            div.input-field.col.s6
              = f.input :name
            div.input-field.col.s6
              = f.input :last_name, input_html: {class: ''}
          div.row
            div.input-field.col.s6
              = f.input :ci_number
            div.input-field.col.s6
              = f.input :birthday
          div.row
            div.input-field.col.s12.right-align
              = f.button :submit